version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "3000:3000"
      - "5001:5001"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    network_mode: host
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mediasoup-client
    environment:
      - REACT_APP_SERVER_URL=https://10.1.26.60:5001
      - PORT=3000
    expose:
      - "3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    network_mode: host

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mediasoup-server
    environment:
      - NODE_ENV=development
      - DOMAIN=https://10.1.26.60
      - PORT=5001
      - SECRET_KEY=secretKey
      - CORS_ORIGIN_LIST='*'
      # MediaSoup specific settings
      - MEDIASOUP_LISTEN_IP=0.0.0.0
      - MEDIASOUP_ANNOUNCED_IP=10.1.26.60
      - MEDIASOUP_MIN_PORT=40000
      - MEDIASOUP_MAX_PORT=40999
      - MEDIASOUP_WORKER_NUM=1
      - DEBUG=mediasoup:*
    expose:
      - "5001"
    volumes:
      - ./server:/app
      - /app/node_modules
      - /var/log/mediasoup:/var/log/mediasoup
    restart: unless-stopped
    network_mode: host
    # MediaSoup RTC ports (for WebRTC)
    ports:
      - "40000-40999:40000-40999/udp"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      - net.core.rmem_max=33554432
      - net.core.wmem_max=33554432 